### ISSUE TITLE
EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by khanrn** [braginteractive/hooch#1]
Hello,

There is an issue coming up when I try to run `gulp` on terminal. It says,
`An error occured: EISDIR: illegal operation on a directory, read`

How to resolve the issue ?
![screenshot_3](https://cloud.githubusercontent.com/assets/6243408/15600666/31b0a9b0-240d-11e6-9036-d7afcfafcaa5.png)

**Comment by braginteractive** [comment]
I noticed this on another theme I was working on. I had to change my sass tasks to the following:

`// Sass
gulp.task('sass', function() {
    return gulp.src('./sass/style.scss')
        .pipe(plumber())
        .pipe(sass(options.sass))
        .pipe(autoprefixer())
        .pipe(gulp.dest('.'))
        .pipe(notify({ title: 'Sass', message: 'sass task complete'  }));
});

// Sass-min - Release build minifies CSS after compiling Sass
gulp.task('sass-min', function() {
    return gulp.src('./sass/style.scss')
        .pipe(plumber())
        .pipe(sass(options.sassmin))
        .pipe(autoprefixer())
        .pipe( rename( { suffix: '.min' } ) )
        .pipe(gulp.dest('.'))
        .pipe(notify({ title: 'Sass', message: 'sass-min task complete' }));
});`

You may have to edit to fit your needs.

**Comment by braginteractive** [comment]
I will push an update in the near future for this issue.

**Comment by encorehe** [comment]
exclude node_modules is ok
